// Generated by CoffeeScript 1.3.3
(function() {

  exports.appName = 'bingo';

  exports.dburl = 'mongodb://localhost:27017/bingo';

  exports.port = 8999;

  exports.throttle = false;

  exports.maintenance = false;

}).call(this);
